select CUSTOMER_ID,NAME,PRODUCT,CATEGORY from CASESTUDY1.ONEDRIVE_CASESTUDY1.CUSTOMER_DATA_SHEET_1
union
SELECT CUSTOMER_ID,NAME,PRODUCT,CATEGORY FROM CASESTUDY1.POSTGRES_CASESTUDY_CASESTUDY1.STG_CUSTOMER_PURCHASES


