select PS.CUSTOMER_ID,PS.NAME,PS.PRODUCT,PS.CATEGORY,PS.PRICE from CASESTUDY1.ONEDRIVE_CASESTUDY1.CUSTOMER_DATA_SHEET_1 AS O
RIGHT JOIN 
(SELECT CUSTOMER_ID,NAME,PRODUCT,CATEGORY,PRICE FROM CASESTUDY1.POSTGRES_CASESTUDY_CASESTUDY1.STG_CUSTOMER_PURCHASES) AS PS
ON O.CUSTOMER_ID=PS.CUSTOMER_ID

